server.port=5551

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:5551/eureka/

spring.application.name=registry-service
spring.profiles.active=dev
