server.port=5552
server.servlet.context-path=/master-service

spring.application.name=master-service
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/master
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.baseline-on-migrate=true

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

eureka.client.service-url.defaultZone=http://localhost:5551/eureka/

#spring.flyway.baseline-on-migrate=true
